version: '3.8'

services:
  valoredash:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
    command: >
      sh -c "
        echo 'server {
          listen 80;
          root /usr/share/nginx/html;
          index index.html;
          location / {
            try_files \$$uri \$$uri/ /index.html;
          }
        }' > /etc/nginx/conf.d/default.conf &&
        echo '<!DOCTYPE html>
        <html>
        <head><title>Valoredash</title></head>
        <body>
          <h1>Valoredash Funcionando!</h1>
          <p>Aplicação deployada com sucesso via Portainer</p>
        </body>
        </html>' > /usr/share/nginx/html/index.html &&
        nginx -g \"daemon off;\"
      "

volumes:
  nginx_conf:
