version: '3.8'

services:
  # Serviço que builda a aplicação (roda uma vez)
  builder:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - build_output:/app/dist
    command: >
      sh -c "
        apk add --no-cache git &&
        rm -rf /app/* /app/.* 2>/dev/null || true &&
        git clone https://github.com/GCalebe/valoredash-v1-48.git /tmp/source &&
        cp -r /tmp/source/* /app/ &&
        cp -r /tmp/source/.* /app/ 2>/dev/null || true &&
        npm ci &&
        npm run build &&
        echo 'Build completed successfully!' &&
        ls -la dist/
      "
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=https://nkyvhwmjuksumizljclc.supabase.co
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5reXZod21qdWtzdW1pemxqY2xjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODI4NzIsImV4cCI6MjA2NTE1ODg3Mn0.JYAUGHTbf9KVPCYFN9IDCm2uRT85cEj9G7llkOcrBEk

  # Serviço que serve a aplicação
  valoredash-app:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - build_output:/usr/share/nginx/html:ro
    depends_on:
      - builder
    command: >
      sh -c "
        echo 'server {
          listen 80;
          root /usr/share/nginx/html;
          index index.html;
          location / {
            try_files \$$uri \$$uri/ /index.html;
          }
          location /health {
            return 200 \"healthy\";
            add_header Content-Type text/plain;
          }
        }' > /etc/nginx/conf.d/default.conf &&
        echo 'Waiting for build files...' &&
        while [ ! -f /usr/share/nginx/html/index.html ]; do sleep 2; done &&
        echo 'Files found, starting nginx...' &&
        nginx -g 'daemon off;'
      "
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  build_output:
