version: '3.8'

services:
  # Build service (roda uma vez para gerar os arquivos)
  builder:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - dist_volume:/app/dist
    command: >
      sh -c "
        npm ci &&
        npm run build &&
        echo 'Build completed successfully!'
      "
    deploy:
      restart_policy:
        condition: none

  # Nginx service (serve os arquivos)
  valoredash-app:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - dist_volume:/usr/share/nginx/html:ro
    environment:
      - NODE_ENV=production
    depends_on:
      - builder
    deploy:
      restart_policy:
        condition: on-failure
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  dist_volume:
